name: "01_dev_caller"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    permissions: #Permission is required if enabling TFSEC == true
      actions: read
      contents: read
      security-events: write
    uses: linh5847/azure-terragrunt-terraform-github-action/.github/workflows/az_tf_plan.yml@development # @development means github branch
    with:
      path: dev ## Path to terraform root module (Required)
      enable_TFSEC: true ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
    secrets:
      arm_client_id: ${{ secrets.DEV_ARM_CLIENT_ID }} ## ARM Client ID
      arm_client_secret: ${{ secrets.DEV_ARM_CLIENT_SECRET }} ## ARM Client Secret
      arm_subscription_id: ${{ secrets.DEV_ARM_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.DEV_ARM_TENANT_ID }} ## ARM Tenant ID

  Deploy_Dev:
    needs: Plan_Dev
    uses: linh5847/azure-terragrunt-terraform-github-action/.github/workflows/az_tf_apply.yml@development
    with:
      path: dev ## Path to terraform root module (Required)
      gh_environment: dev ## GH Environment. Default=null - (Optional)
    secrets:
      arm_client_id: ${{ secrets.DEV_ARM_CLIENT_ID }} ## ARM Client ID
      arm_client_secret: ${{ secrets.DEV_ARM_CLIENT_SECRET }} ## ARM Client Secret
      arm_subscription_id: ${{ secrets.DEV_ARM_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.DEV_ARM_TENANT_ID }} ## ARM Tenant ID
