name: "caller"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    permissions: #Permission is required if enabling TFSEC == true
      actions: read
      contents: read
      security-events: write
    uses: azure-terragrunt-terraform-github-action/.github/workflows/az_tf_plan.yml@master
    with:
      path: dev ## Path to terraform root module (Required)
      enable_TFSEC: true ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
    secrets:
      arm_client_id: ${{ secrets.DEV_ARM_CLIENT_ID }} ## ARM Client ID
      arm_client_secret: ${{ secrets.DEV_ARM_CLIENT_SECRET }} ## ARM Client Secret
      arm_subscription_id: ${{ secrets.DEV_ARM_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.DEV_ARM_TENANT_ID }} ## ARM Tenant ID

  Deploy_Dev:
    needs: Plan_Dev
    uses: azure-terragrunt-terraform-github-action/.github/workflows/az_tf_apply.yml@master
    with:
      path: dev ## Path to terraform root module (Required)
      tgh_environment: dev ## GH Environment. Default=null - (Optional)
    secrets:
      arm_client_id: ${{ secrets.DEV_ARM_CLIENT_ID }} ## ARM Client ID
      arm_client_secret: ${{ secrets.DEV_ARM_CLIENT_SECRET }} ## ARM Client Secret
      arm_subscription_id: ${{ secrets.DEV_ARM_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.DEV_ARM_TENANT_ID }} ## ARM Tenant ID

  Plan_Stage:
    permissions: #Permission is required if enabling TFSEC == true
      actions: read
      contents: read
      security-events: write
    uses: azure-terragrunt-terraform-github-action/.github/workflows/az_tf_plan.yml@master
    with:
      path: stage
      enable_TFSEC: true
    secrets:
      arm_client_id: ${{ secrets.STAGE_ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.STAGE_ARM_CLIENT_SECRET }}
      arm_subscription_id: ${{ secrets.STAGE_ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ secrets.STAGE_ARM_TENANT_ID }}

  Deploy_Stage:
    needs: [Plan_Stage, Deploy_Dev]
    uses: azure-terragrunt-terraform-github-action/.github/workflows/az_tf_apply.yml@master
    with:
      path: stage
      gh_environment: stage
    secrets:
      arm_client_id: ${{ secrets.STAGE_ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.STAGE_ARM_CLIENT_SECRET }}
      arm_subscription_id: ${{ secrets.STAGE_ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ secrets.STAGE_ARM_TENANT_ID }}

  Plan_Prod:
    permissions: #Permission is required if enabling TFSEC == true
      actions: read
      contents: read
      security-events: write
    uses: azure-terragrunt-terraform-github-action/.github/workflows/az_tf_plan.yml@master
    with:
      path: prod
      enable_TFSEC: true
    secrets:
      arm_client_id: ${{ secrets.PROD_ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.PROD_ARM_CLIENT_SECRET }}
      arm_subscription_id: ${{ secrets.PROD_ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ secrets.PROD_ARM_TENANT_ID }}

  Deploy_Prod:
    needs: [Plan_Prod, Deploy_Stage]
    uses: azure-terragrunt-terraform-github-action/.github/workflows/az_tf_apply.yml@master
    with:
      path: prod
      gh_environment: prod
    secrets:
      arm_client_id: ${{ secrets.PROD_ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.PROD_ARM_CLIENT_SECRET }}
      arm_subscription_id: ${{ secrets.PROD_ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ secrets.PROD_ARM_TENANT_ID }}
