name: "prod_caller"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Plan_Prod:
    permissions: #Permission is required if enabling TFSEC == true
      actions: read
      contents: read
      security-events: write
    uses: linh5847/azure-terragrunt-terraform-github-action/.github/workflows/az_tf_plan.yml@main
    with:
      path: prod
      enable_TFSEC: true
    secrets:
      arm_client_id: ${{ secrets.PROD_ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.PROD_ARM_CLIENT_SECRET }}
      arm_subscription_id: ${{ secrets.PROD_ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ secrets.PROD_ARM_TENANT_ID }}

  Deploy_Prod:
    needs: [Plan_Prod] # Depending on the plan
    uses: linh5847/azure-terragrunt-terraform-github-action/.github/workflows/az_tf_apply.yml@main
    with:
      path: prod
      gh_environment: prod
    secrets:
      arm_client_id: ${{ secrets.PROD_ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.PROD_ARM_CLIENT_SECRET }}
      arm_subscription_id: ${{ secrets.PROD_ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ secrets.PROD_ARM_TENANT_ID }}
